name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "src/**"
      - ".github/workflows/docker-image.yml"
      - "package.json"
  #pull_request:
  #  branches: [ "main" ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    - name: Build the Docker image
      run: docker buildx build --platform linux/amd64,linux/arm64 \
           -t urielch/dyn-ingress:latest \
           -t urielch/dyn-ingress:$(date +%Y-%m-%d_%H%M%S) \
           --push .
