name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.0.0
    - name: Build the Docker image
      run: docker buildx build --platform linux/amd64,linux/arm64 -t urielch/dyn-ingress:latest --push .
#     run: docker build . --file Dockerfile --tag my-image-name:$(date +%s) 
